import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateWarehouseLocationtable1763836624456 implements MigrationInterface {
    name = 'CreateWarehouseLocationtable1763836624456'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tax_return" DROP CONSTRAINT "FK_5b369333589e163dcfb2e14637d"`);
        await queryRunner.query(`ALTER TABLE "bank_statement" DROP CONSTRAINT "FK_4c70822ddbd990361ff7e445a80"`);
        await queryRunner.query(`ALTER TABLE "financial_others" DROP CONSTRAINT "FK_4779a5a00fc5f60d9d314e126d8"`);
        await queryRunner.query(`ALTER TABLE "registration_application" DROP CONSTRAINT "FK_79bad6b8ec15830e8d666eaf05d"`);
        await queryRunner.query(`CREATE TABLE "facility" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseLocationId" uuid NOT NULL, "facilityName" character varying(200) NOT NULL, "storageFacilityType" character varying(100) NOT NULL, "address" text NOT NULL, "numberOfStorageUnits" character varying(50) NOT NULL, "individualCapacityPerUnit" character varying(50) NOT NULL, "totalCapacity" character varying(50) NOT NULL, "storageFacilitiesAppliedFor" character varying(100) NOT NULL, "produceForAccreditation" json NOT NULL, "totalCapacityAppliedFor" character varying(50) NOT NULL, "plinthHeight" character varying(50) NOT NULL, "length" character varying(50) NOT NULL, "width" character varying(50) NOT NULL, "height" character varying(50) NOT NULL, "ownership" character varying(100) NOT NULL, "leaseDuration" date, "borrowerCodeOfPropertyOwner" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_12a1c759cb8650f234a626fee5" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_07c6c82781d105a680b5c265be6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseLocationId" uuid NOT NULL, "name" character varying(200) NOT NULL, "email" character varying(200) NOT NULL, "phoneNumber" character varying(50), "mobileNumber" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_2eee0db85ff2fbb504a8b7e733" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_2cbbe00f59ab6b3bb5b8d19f989" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jurisdiction" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseLocationId" uuid NOT NULL, "jurisdictionalPoliceStationName" character varying(200) NOT NULL, "policeStationDistance" character varying(50) NOT NULL, "nearestFireStationName" character varying(200) NOT NULL, "fireStationDistance" character varying(50) NOT NULL, "numberOfEntryAndExit" character varying(50) NOT NULL, "compoundWallFencing" boolean NOT NULL DEFAULT false, "heightOfCompoundWall" character varying(50), "compoundWallBarbedFencing" boolean NOT NULL DEFAULT false, "damageOnCompoundWall" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_e2e12a5073b2befa4994b65b1b" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_0f85126272d91bb550d40207022" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "security" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseLocationId" uuid NOT NULL, "guardsDeployed" character varying(50) NOT NULL, "NumberOfCameras" character varying(50) NOT NULL, "otherSecurityMeasures" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_5239359785bdf91752135720e0" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_148e8beb2eb8f65efdb658cb3fd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fire_safety" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseLocationId" uuid NOT NULL, "fireExtinguishers" character varying(50) NOT NULL, "fireBuckets" character varying(50) NOT NULL, "waterArrangements" boolean NOT NULL DEFAULT false, "fireSafetyAlarms" boolean NOT NULL DEFAULT false, "otherFireSafetyMeasures" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_7ec3b887ddd5a4f2fd5ce5011b" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_5d71d5383538f84dec6c2725938" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "weighing" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseLocationId" uuid NOT NULL, "weighbridgeAvailable" boolean NOT NULL DEFAULT false, "weighbridgeLocation" character varying(200) NOT NULL, "weighbridgeCapacity" character varying(50) NOT NULL, "weighbridgeMakeModel" character varying(200), "weighbridgeInstallationDate" date, "weighbridgeCalibrationStatus" date, "weighbridgeNextCalibrationDueDate" date, "weighbridgeOwnerOperatorName" character varying(200), "weighbridgeAddressLocation" text, "weighbridgeDistanceFromFacility" character varying(50), "weighbridgeCalibrationCertificate" character varying(500), "laboratoryFacility" boolean NOT NULL DEFAULT false, "minimumLabEquipmentExist" boolean NOT NULL DEFAULT false, "equipmentCalibrated" boolean NOT NULL DEFAULT false, "washroomsExist" boolean NOT NULL DEFAULT false, "waterAvailability" boolean NOT NULL DEFAULT false, "officeInternetFacility" boolean NOT NULL DEFAULT false, "electricityAvailable" boolean NOT NULL DEFAULT false, "gasAvailable" boolean NOT NULL DEFAULT false, "generatorAvailable" boolean NOT NULL DEFAULT false, "otherUtilitiesFacilities" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_c221f55a67dead6bcfeb625013" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_600690680efe2fc76418a7b9b6a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "academic_qualifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "humanResourceId" uuid NOT NULL, "degree" character varying(200) NOT NULL, "major" character varying(200) NOT NULL, "institute" character varying(300) NOT NULL, "country" character varying(100) NOT NULL, "yearOfPassing" character varying(50) NOT NULL, "grade" character varying(50) NOT NULL, "academicCertificate" character varying(500), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fb5a5888691cc161ed2a8ece5de" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "professional_qualifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "humanResourceId" uuid NOT NULL, "certificationTitle" character varying(200) NOT NULL, "issuingBody" character varying(200) NOT NULL, "country" character varying(100) NOT NULL, "dateOfAward" date, "membershipNumber" character varying(100) NOT NULL, "hasExpiryDate" boolean NOT NULL DEFAULT false, "professionalCertificate" character varying(500), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_18be4f2304a132fea4fc8b3dddb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trainings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "humanResourceId" uuid NOT NULL, "trainingTitle" character varying(200) NOT NULL, "conductedBy" character varying(200) NOT NULL, "trainingType" character varying(100) NOT NULL, "duration" character varying(50) NOT NULL, "dateOfCompletion" date, "trainingCertificate" character varying(500), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b67237502b175163e47dc85018d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "professional_experiences" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "humanResourceId" uuid NOT NULL, "positionHeld" character varying(200) NOT NULL, "organizationName" character varying(300) NOT NULL, "organizationAddress" text NOT NULL, "natureOfOrganization" character varying(200) NOT NULL, "dateOfAppointment" date, "dateOfLeaving" date, "duration" character varying(50) NOT NULL, "responsibilities" text NOT NULL, "experienceLetter" character varying(500), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_55d059b6555c89f27f2cf9dcfb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "human_resources" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "warehouseLocationId" uuid NOT NULL, "fullName" character varying(200) NOT NULL, "fathersHusbandsName" character varying(200) NOT NULL, "cnicPassport" character varying(50) NOT NULL, "photograph" character varying(500), "nationality" character varying(100) NOT NULL, "dateOfBirth" date, "residentialAddress" text NOT NULL, "businessAddress" text NOT NULL, "telephoneNumber" character varying(50) NOT NULL, "mobileNumber" character varying(50) NOT NULL, "email" character varying(200) NOT NULL, "hrNationalTaxNumber" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_42b0f8645160e15063c43070e95" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."warehouse_location_status_enum" AS ENUM('PENDING', 'IN_PROCESS', 'APPROVED', 'REJECTED', 'DRAFT', 'SUBMITTED')`);
        await queryRunner.query(`CREATE TABLE "warehouse_location" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "userId" uuid NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "status" "public"."warehouse_location_status_enum" NOT NULL DEFAULT 'DRAFT', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "facilityId" uuid, "contactId" uuid, "jurisdictionId" uuid, "securityId" uuid, "fireSafetyId" uuid, "weighingId" uuid, CONSTRAINT "REL_344fa3e2d516e832b9b2c11a02" UNIQUE ("facilityId"), CONSTRAINT "REL_cd68d294d390d33ceb835fa355" UNIQUE ("contactId"), CONSTRAINT "REL_ef5df3fd20750b9bf62bd94f3d" UNIQUE ("jurisdictionId"), CONSTRAINT "REL_06f7a298814430d169473698fa" UNIQUE ("securityId"), CONSTRAINT "REL_c084481111f90eb63dc151ec09" UNIQUE ("fireSafetyId"), CONSTRAINT "REL_0994da10970b1d7f23ff089880" UNIQUE ("weighingId"), CONSTRAINT "PK_8b5305b2492ac33409546e4aa08" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "tax_return" DROP COLUMN "document"`);
        await queryRunner.query(`ALTER TABLE "bank_statement" DROP COLUMN "document"`);
        await queryRunner.query(`ALTER TABLE "financial_others" DROP COLUMN "document"`);
        await queryRunner.query(`ALTER TABLE "registration_application" DROP CONSTRAINT "UQ_79bad6b8ec15830e8d666eaf05d"`);
        await queryRunner.query(`ALTER TABLE "registration_application" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TYPE "public"."warehouse_operator_application_request_status_enum" RENAME TO "warehouse_operator_application_request_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."warehouse_operator_application_request_status_enum" AS ENUM('PENDING', 'IN_PROCESS', 'APPROVED', 'REJECTED', 'DRAFT', 'SUBMITTED', 'RESUBMITTED')`);
        await queryRunner.query(`ALTER TABLE "warehouse_operator_application_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "warehouse_operator_application_request" ALTER COLUMN "status" TYPE "public"."warehouse_operator_application_request_status_enum" USING "status"::"text"::"public"."warehouse_operator_application_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "warehouse_operator_application_request" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."warehouse_operator_application_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "facility" ADD CONSTRAINT "FK_12a1c759cb8650f234a626fee53" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact" ADD CONSTRAINT "FK_2eee0db85ff2fbb504a8b7e733e" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisdiction" ADD CONSTRAINT "FK_e2e12a5073b2befa4994b65b1b7" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security" ADD CONSTRAINT "FK_5239359785bdf91752135720e0b" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fire_safety" ADD CONSTRAINT "FK_7ec3b887ddd5a4f2fd5ce5011b1" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighing" ADD CONSTRAINT "FK_c221f55a67dead6bcfeb6250132" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "academic_qualifications" ADD CONSTRAINT "FK_a85c040260493c0875d59bd0ba8" FOREIGN KEY ("humanResourceId") REFERENCES "human_resources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professional_qualifications" ADD CONSTRAINT "FK_c880d0618dda378eb0a66bd5a4a" FOREIGN KEY ("humanResourceId") REFERENCES "human_resources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trainings" ADD CONSTRAINT "FK_046b481d40336c80bf8c3b89576" FOREIGN KEY ("humanResourceId") REFERENCES "human_resources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "professional_experiences" ADD CONSTRAINT "FK_e3b820d925d05523dbeecfe8d89" FOREIGN KEY ("humanResourceId") REFERENCES "human_resources"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "human_resources" ADD CONSTRAINT "FK_e77478e45df08c6f41ff2227674" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" ADD CONSTRAINT "FK_9e02a8a8fe32afc1d79035b516a" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" ADD CONSTRAINT "FK_344fa3e2d516e832b9b2c11a025" FOREIGN KEY ("facilityId") REFERENCES "facility"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" ADD CONSTRAINT "FK_cd68d294d390d33ceb835fa3558" FOREIGN KEY ("contactId") REFERENCES "contact"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" ADD CONSTRAINT "FK_ef5df3fd20750b9bf62bd94f3d5" FOREIGN KEY ("jurisdictionId") REFERENCES "jurisdiction"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" ADD CONSTRAINT "FK_06f7a298814430d169473698fa0" FOREIGN KEY ("securityId") REFERENCES "security"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" ADD CONSTRAINT "FK_c084481111f90eb63dc151ec09a" FOREIGN KEY ("fireSafetyId") REFERENCES "fire_safety"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" ADD CONSTRAINT "FK_0994da10970b1d7f23ff0898809" FOREIGN KEY ("weighingId") REFERENCES "weighing"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "warehouse_location" DROP CONSTRAINT "FK_0994da10970b1d7f23ff0898809"`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" DROP CONSTRAINT "FK_c084481111f90eb63dc151ec09a"`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" DROP CONSTRAINT "FK_06f7a298814430d169473698fa0"`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" DROP CONSTRAINT "FK_ef5df3fd20750b9bf62bd94f3d5"`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" DROP CONSTRAINT "FK_cd68d294d390d33ceb835fa3558"`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" DROP CONSTRAINT "FK_344fa3e2d516e832b9b2c11a025"`);
        await queryRunner.query(`ALTER TABLE "warehouse_location" DROP CONSTRAINT "FK_9e02a8a8fe32afc1d79035b516a"`);
        await queryRunner.query(`ALTER TABLE "human_resources" DROP CONSTRAINT "FK_e77478e45df08c6f41ff2227674"`);
        await queryRunner.query(`ALTER TABLE "professional_experiences" DROP CONSTRAINT "FK_e3b820d925d05523dbeecfe8d89"`);
        await queryRunner.query(`ALTER TABLE "trainings" DROP CONSTRAINT "FK_046b481d40336c80bf8c3b89576"`);
        await queryRunner.query(`ALTER TABLE "professional_qualifications" DROP CONSTRAINT "FK_c880d0618dda378eb0a66bd5a4a"`);
        await queryRunner.query(`ALTER TABLE "academic_qualifications" DROP CONSTRAINT "FK_a85c040260493c0875d59bd0ba8"`);
        await queryRunner.query(`ALTER TABLE "weighing" DROP CONSTRAINT "FK_c221f55a67dead6bcfeb6250132"`);
        await queryRunner.query(`ALTER TABLE "fire_safety" DROP CONSTRAINT "FK_7ec3b887ddd5a4f2fd5ce5011b1"`);
        await queryRunner.query(`ALTER TABLE "security" DROP CONSTRAINT "FK_5239359785bdf91752135720e0b"`);
        await queryRunner.query(`ALTER TABLE "jurisdiction" DROP CONSTRAINT "FK_e2e12a5073b2befa4994b65b1b7"`);
        await queryRunner.query(`ALTER TABLE "contact" DROP CONSTRAINT "FK_2eee0db85ff2fbb504a8b7e733e"`);
        await queryRunner.query(`ALTER TABLE "facility" DROP CONSTRAINT "FK_12a1c759cb8650f234a626fee53"`);
        await queryRunner.query(`CREATE TYPE "public"."warehouse_operator_application_request_status_enum_old" AS ENUM('PENDING', 'IN_PROCESS', 'APPROVED', 'REJECTED', 'DRAFT', 'SUBMITTED', 'RESUBMITTED', 'SENT_TO_HOD')`);
        await queryRunner.query(`ALTER TABLE "warehouse_operator_application_request" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "warehouse_operator_application_request" ALTER COLUMN "status" TYPE "public"."warehouse_operator_application_request_status_enum_old" USING "status"::"text"::"public"."warehouse_operator_application_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "warehouse_operator_application_request" ALTER COLUMN "status" SET DEFAULT 'PENDING'`);
        await queryRunner.query(`DROP TYPE "public"."warehouse_operator_application_request_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."warehouse_operator_application_request_status_enum_old" RENAME TO "warehouse_operator_application_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "registration_application" ADD "userId" uuid`);
        await queryRunner.query(`ALTER TABLE "registration_application" ADD CONSTRAINT "UQ_79bad6b8ec15830e8d666eaf05d" UNIQUE ("userId")`);
        await queryRunner.query(`ALTER TABLE "financial_others" ADD "document" uuid`);
        await queryRunner.query(`ALTER TABLE "bank_statement" ADD "document" uuid`);
        await queryRunner.query(`ALTER TABLE "tax_return" ADD "document" uuid`);
        await queryRunner.query(`DROP TABLE "warehouse_location"`);
        await queryRunner.query(`DROP TYPE "public"."warehouse_location_status_enum"`);
        await queryRunner.query(`DROP TABLE "human_resources"`);
        await queryRunner.query(`DROP TABLE "professional_experiences"`);
        await queryRunner.query(`DROP TABLE "trainings"`);
        await queryRunner.query(`DROP TABLE "professional_qualifications"`);
        await queryRunner.query(`DROP TABLE "academic_qualifications"`);
        await queryRunner.query(`DROP TABLE "weighing"`);
        await queryRunner.query(`DROP TABLE "fire_safety"`);
        await queryRunner.query(`DROP TABLE "security"`);
        await queryRunner.query(`DROP TABLE "jurisdiction"`);
        await queryRunner.query(`DROP TABLE "contact"`);
        await queryRunner.query(`DROP TABLE "facility"`);
        await queryRunner.query(`ALTER TABLE "registration_application" ADD CONSTRAINT "FK_79bad6b8ec15830e8d666eaf05d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "financial_others" ADD CONSTRAINT "FK_4779a5a00fc5f60d9d314e126d8" FOREIGN KEY ("document") REFERENCES "warehouse_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_statement" ADD CONSTRAINT "FK_4c70822ddbd990361ff7e445a80" FOREIGN KEY ("document") REFERENCES "warehouse_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tax_return" ADD CONSTRAINT "FK_5b369333589e163dcfb2e14637d" FOREIGN KEY ("document") REFERENCES "warehouse_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
    }

}
