import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateFacilityHistoryTable1766157669279 implements MigrationInterface {
    name = 'CreateFacilityHistoryTable1766157669279'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "weighing_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "weighingId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "weighbridgeAvailable" boolean NOT NULL DEFAULT false, "weighbridgeLocation" character varying(200) NOT NULL, "weighbridgeCapacity" character varying(50) NOT NULL, "weighbridgeMakeModel" character varying(200), "weighbridgeInstallationDate" date, "weighbridgeCalibrationStatus" date, "weighbridgeNextCalibrationDueDate" date, "weighbridgeOwnerOperatorName" character varying(200), "weighbridgeAddressLocation" text, "weighbridgeDistanceFromFacility" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "weighbridgeCalibrationCertificate" uuid, CONSTRAINT "REL_70b1f283730c20f6dde9fde6b2" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_ad5e721897de3b8118f7c806d32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "technical_qualitative_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "technicalQualitativeId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "laboratoryFacility" boolean NOT NULL DEFAULT false, "minimumLabEquipmentExist" boolean NOT NULL DEFAULT false, "equipmentCalibrated" boolean NOT NULL DEFAULT false, "washroomsExist" boolean NOT NULL DEFAULT false, "waterAvailability" boolean NOT NULL DEFAULT false, "officeInternetFacility" boolean NOT NULL DEFAULT false, "electricityAvailable" boolean NOT NULL DEFAULT false, "gasAvailable" boolean NOT NULL DEFAULT false, "generatorAvailable" boolean NOT NULL DEFAULT false, "otherUtilitiesFacilities" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_1fce116ee6729a872de763e022" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_22cc2033eb671c980882156c451" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jurisdiction_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jurisdictionId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "jurisdictionalPoliceStationName" character varying(200) NOT NULL, "policeStationDistance" character varying(50) NOT NULL, "nearestFireStationName" character varying(200) NOT NULL, "fireStationDistance" character varying(50) NOT NULL, "numberOfEntryAndExit" character varying(50) NOT NULL, "compoundWallFencing" boolean NOT NULL DEFAULT false, "heightOfCompoundWall" character varying(50), "compoundWallBarbedFencing" boolean NOT NULL DEFAULT false, "damageOnCompoundWall" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_10313eb74a5f7c95770b0c27d0" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_1bc901d5b65d924597f06a5d26c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "security_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "securityId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "guardsDeployed" character varying(50) NOT NULL, "NumberOfCameras" character varying(50) NOT NULL, "otherSecurityMeasures" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_022e8d2fc65553fb7470c3cf3c" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_dd1be0a34075d15c0822ba3c544" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fire_safety_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fireSafetyId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "fireExtinguishers" character varying(50) NOT NULL, "fireBuckets" character varying(50) NOT NULL, "waterArrangements" boolean NOT NULL DEFAULT false, "fireSafetyAlarms" boolean NOT NULL DEFAULT false, "otherFireSafetyMeasures" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_26366890b5ae02523c8bb61e51" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_a58f300253369e244d53283f163" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facility_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "facilityId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "facilityName" character varying(200) NOT NULL, "storageFacilityType" character varying(100) NOT NULL, "address" text NOT NULL, "numberOfStorageUnits" character varying(50) NOT NULL, "individualCapacityPerUnit" character varying(50) NOT NULL, "totalCapacity" character varying(50) NOT NULL, "storageFacilitiesAppliedFor" character varying(100) NOT NULL, "produceForAccreditation" json NOT NULL, "totalCapacityAppliedFor" character varying(50) NOT NULL, "plinthHeight" character varying(50) NOT NULL, "length" character varying(50) NOT NULL, "width" character varying(50) NOT NULL, "height" character varying(50) NOT NULL, "ownership" character varying(100) NOT NULL, "leaseDuration" date, "borrowerCodeOfPropertyOwner" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_b7133352bed6d2c7225e8814a0" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_1b0e82d4fc5c7254b551add8afd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contactId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "name" character varying(200) NOT NULL, "email" character varying(200) NOT NULL, "phoneNumber" character varying(50), "mobileNumber" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_0c3dc8902a378fab9b3fe15d81" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_68d75ef80ec536aee6b570ebaa6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "weighing_history" ADD CONSTRAINT "FK_420976612b58fe9bec06d965c93" FOREIGN KEY ("weighingId") REFERENCES "weighing"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighing_history" ADD CONSTRAINT "FK_d07a787a1c21a374b1d68796a6e" FOREIGN KEY ("weighbridgeCalibrationCertificate") REFERENCES "warehouse_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighing_history" ADD CONSTRAINT "FK_70b1f283730c20f6dde9fde6b21" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" ADD CONSTRAINT "FK_2d1b3ee6d0b70bf533902a47b5d" FOREIGN KEY ("technicalQualitativeId") REFERENCES "technical_qualitative"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" ADD CONSTRAINT "FK_1fce116ee6729a872de763e0225" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" ADD CONSTRAINT "FK_cd45d6d0937d5ac6a6a83477b9c" FOREIGN KEY ("jurisdictionId") REFERENCES "jurisdiction"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" ADD CONSTRAINT "FK_10313eb74a5f7c95770b0c27d03" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_history" ADD CONSTRAINT "FK_3888228dd434c0e526310620cf8" FOREIGN KEY ("securityId") REFERENCES "security"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_history" ADD CONSTRAINT "FK_022e8d2fc65553fb7470c3cf3cd" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" ADD CONSTRAINT "FK_818e10abf5d99a5e8fca4e2492e" FOREIGN KEY ("fireSafetyId") REFERENCES "fire_safety"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" ADD CONSTRAINT "FK_26366890b5ae02523c8bb61e510" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility_history" ADD CONSTRAINT "FK_98b9bcef9313f59c4be41e73ce8" FOREIGN KEY ("facilityId") REFERENCES "facility"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility_history" ADD CONSTRAINT "FK_b7133352bed6d2c7225e8814a0b" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_history" ADD CONSTRAINT "FK_4a93b3794827c600f020d827d05" FOREIGN KEY ("contactId") REFERENCES "contact"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_history" ADD CONSTRAINT "FK_0c3dc8902a378fab9b3fe15d818" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "contact_history" DROP CONSTRAINT "FK_0c3dc8902a378fab9b3fe15d818"`);
        await queryRunner.query(`ALTER TABLE "contact_history" DROP CONSTRAINT "FK_4a93b3794827c600f020d827d05"`);
        await queryRunner.query(`ALTER TABLE "facility_history" DROP CONSTRAINT "FK_b7133352bed6d2c7225e8814a0b"`);
        await queryRunner.query(`ALTER TABLE "facility_history" DROP CONSTRAINT "FK_98b9bcef9313f59c4be41e73ce8"`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" DROP CONSTRAINT "FK_26366890b5ae02523c8bb61e510"`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" DROP CONSTRAINT "FK_818e10abf5d99a5e8fca4e2492e"`);
        await queryRunner.query(`ALTER TABLE "security_history" DROP CONSTRAINT "FK_022e8d2fc65553fb7470c3cf3cd"`);
        await queryRunner.query(`ALTER TABLE "security_history" DROP CONSTRAINT "FK_3888228dd434c0e526310620cf8"`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" DROP CONSTRAINT "FK_10313eb74a5f7c95770b0c27d03"`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" DROP CONSTRAINT "FK_cd45d6d0937d5ac6a6a83477b9c"`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" DROP CONSTRAINT "FK_1fce116ee6729a872de763e0225"`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" DROP CONSTRAINT "FK_2d1b3ee6d0b70bf533902a47b5d"`);
        await queryRunner.query(`ALTER TABLE "weighing_history" DROP CONSTRAINT "FK_70b1f283730c20f6dde9fde6b21"`);
        await queryRunner.query(`ALTER TABLE "weighing_history" DROP CONSTRAINT "FK_d07a787a1c21a374b1d68796a6e"`);
        await queryRunner.query(`ALTER TABLE "weighing_history" DROP CONSTRAINT "FK_420976612b58fe9bec06d965c93"`);
        await queryRunner.query(`DROP TABLE "contact_history"`);
        await queryRunner.query(`DROP TABLE "facility_history"`);
        await queryRunner.query(`DROP TABLE "fire_safety_history"`);
        await queryRunner.query(`DROP TABLE "security_history"`);
        await queryRunner.query(`DROP TABLE "jurisdiction_history"`);
        await queryRunner.query(`DROP TABLE "technical_qualitative_history"`);
        await queryRunner.query(`DROP TABLE "weighing_history"`);
    }

}
