import { MigrationInterface, QueryRunner } from "typeorm";

export class CreateFacilityHistoryTable1766156997826 implements MigrationInterface {
    name = 'CreateFacilityHistoryTable1766156997826'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_role"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_role_permissions_permission"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_user_roles_user"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_user_roles_role"`);
        await queryRunner.query(`ALTER TABLE "registration_application_details" DROP CONSTRAINT "FK_registration_application_details_document_type"`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" DROP CONSTRAINT "FK_admin_registration_documents_applicationId"`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" DROP CONSTRAINT "FK_admin_registration_documents_detailId"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_form_fields_formId"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_form_fields_document_type"`);
        await queryRunner.query(`ALTER TABLE "form_submission_values" DROP CONSTRAINT "FK_form_submission_values_submissionId"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_form_submissions_formId"`);
        await queryRunner.query(`ALTER TABLE "form_fields_requests" DROP CONSTRAINT "FK_form_fields_requests_formRequestId"`);
        await queryRunner.query(`ALTER TABLE "form_requests" DROP CONSTRAINT "FK_form_requests_formId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_roleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_permissionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_roleId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_settings_key"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_document_types_deletedAt"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_registration_application_details_documentTypeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_registration_application_applicationId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_registration_documents_applicationId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_admin_registration_documents_detailId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forms_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forms_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forms_isPublic"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forms_isActive"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_forms_version"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_formId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_fieldKey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_type"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_formId_fieldKey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_documentTypeId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submission_values_submissionId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submission_values_fieldKey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submissions_formId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submissions_userId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_submissions_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_requests_formRequestId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_requests_fieldKey"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_fields_requests_action"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_requests_formId"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_requests_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_requests_slug"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_form_requests_requestedBy"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "UQ_role_permissions"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "UQ_user_roles"`);
        await queryRunner.query(`CREATE TABLE "weighing_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "weighingId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "weighbridgeAvailable" boolean NOT NULL DEFAULT false, "weighbridgeLocation" character varying(200) NOT NULL, "weighbridgeCapacity" character varying(50) NOT NULL, "weighbridgeMakeModel" character varying(200), "weighbridgeInstallationDate" date, "weighbridgeCalibrationStatus" date, "weighbridgeNextCalibrationDueDate" date, "weighbridgeOwnerOperatorName" character varying(200), "weighbridgeAddressLocation" text, "weighbridgeDistanceFromFacility" character varying(50), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "weighbridgeCalibrationCertificate" uuid, CONSTRAINT "REL_70b1f283730c20f6dde9fde6b2" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_ad5e721897de3b8118f7c806d32" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "technical_qualitative_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "technicalQualitativeId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "laboratoryFacility" boolean NOT NULL DEFAULT false, "minimumLabEquipmentExist" boolean NOT NULL DEFAULT false, "equipmentCalibrated" boolean NOT NULL DEFAULT false, "washroomsExist" boolean NOT NULL DEFAULT false, "waterAvailability" boolean NOT NULL DEFAULT false, "officeInternetFacility" boolean NOT NULL DEFAULT false, "electricityAvailable" boolean NOT NULL DEFAULT false, "gasAvailable" boolean NOT NULL DEFAULT false, "generatorAvailable" boolean NOT NULL DEFAULT false, "otherUtilitiesFacilities" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_1fce116ee6729a872de763e022" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_22cc2033eb671c980882156c451" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "jurisdiction_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "jurisdictionId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "jurisdictionalPoliceStationName" character varying(200) NOT NULL, "policeStationDistance" character varying(50) NOT NULL, "nearestFireStationName" character varying(200) NOT NULL, "fireStationDistance" character varying(50) NOT NULL, "numberOfEntryAndExit" character varying(50) NOT NULL, "compoundWallFencing" boolean NOT NULL DEFAULT false, "heightOfCompoundWall" character varying(50), "compoundWallBarbedFencing" boolean NOT NULL DEFAULT false, "damageOnCompoundWall" boolean NOT NULL DEFAULT false, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_10313eb74a5f7c95770b0c27d0" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_1bc901d5b65d924597f06a5d26c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "security_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "securityId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "guardsDeployed" character varying(50) NOT NULL, "NumberOfCameras" character varying(50) NOT NULL, "otherSecurityMeasures" character varying(100) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_022e8d2fc65553fb7470c3cf3c" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_dd1be0a34075d15c0822ba3c544" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "fire_safety_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "fireSafetyId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "fireExtinguishers" character varying(50) NOT NULL, "fireBuckets" character varying(50) NOT NULL, "waterArrangements" boolean NOT NULL DEFAULT false, "fireSafetyAlarms" boolean NOT NULL DEFAULT false, "otherFireSafetyMeasures" text, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_26366890b5ae02523c8bb61e51" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_a58f300253369e244d53283f163" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "facility_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "facilityId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "facilityName" character varying(200) NOT NULL, "storageFacilityType" character varying(100) NOT NULL, "address" text NOT NULL, "numberOfStorageUnits" character varying(50) NOT NULL, "individualCapacityPerUnit" character varying(50) NOT NULL, "totalCapacity" character varying(50) NOT NULL, "storageFacilitiesAppliedFor" character varying(100) NOT NULL, "produceForAccreditation" json NOT NULL, "totalCapacityAppliedFor" character varying(50) NOT NULL, "plinthHeight" character varying(50) NOT NULL, "length" character varying(50) NOT NULL, "width" character varying(50) NOT NULL, "height" character varying(50) NOT NULL, "ownership" character varying(100) NOT NULL, "leaseDuration" date, "borrowerCodeOfPropertyOwner" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_b7133352bed6d2c7225e8814a0" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_1b0e82d4fc5c7254b551add8afd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contact_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "contactId" uuid NOT NULL, "warehouseLocationId" uuid NOT NULL, "name" character varying(200) NOT NULL, "email" character varying(200) NOT NULL, "phoneNumber" character varying(50), "mobileNumber" character varying(50) NOT NULL, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_0c3dc8902a378fab9b3fe15d81" UNIQUE ("warehouseLocationId"), CONSTRAINT "PK_68d75ef80ec536aee6b570ebaa6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."refreshToken" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."passwordResetToken" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."passwordResetExpires" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."otp" IS NULL`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."otpExpires" IS NULL`);
        await queryRunner.query(`ALTER TABLE "registration_application" DROP CONSTRAINT "FK_5ce51bfeedd4654c6cbd1b563a9"`);
        await queryRunner.query(`ALTER TABLE "registration_application" ADD CONSTRAINT "UQ_5ce51bfeedd4654c6cbd1b563a9" UNIQUE ("applicationTypeId")`);
        await queryRunner.query(`ALTER TABLE "form_fields_requests" ALTER COLUMN "width" SET NOT NULL`);
        await queryRunner.query(`ALTER TYPE "public"."form_request_status_enum" RENAME TO "form_request_status_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."form_requests_status_enum" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "form_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form_requests" ALTER COLUMN "status" TYPE "public"."form_requests_status_enum" USING "status"::"text"::"public"."form_requests_status_enum"`);
        await queryRunner.query(`ALTER TABLE "form_requests" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."form_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "UQ_d430a02aad006d8a70f3acd7d03" UNIQUE ("roleId", "permissionId")`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "UQ_88481b0c4ed9ada47e9fdd67475" UNIQUE ("userId", "roleId")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_472b25323af01488f1f66a06b67" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_86033897c009fcca8b6505d6be2" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_application_details" ADD CONSTRAINT "FK_4860566b6279bc22f26a96f4ffc" FOREIGN KEY ("documentTypeId") REFERENCES "document_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "registration_application" ADD CONSTRAINT "FK_5ce51bfeedd4654c6cbd1b563a9" FOREIGN KEY ("applicationTypeId") REFERENCES "application_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" ADD CONSTRAINT "FK_1ae12e3d6aa7da17033a35d14aa" FOREIGN KEY ("applicationId") REFERENCES "registration_application"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" ADD CONSTRAINT "FK_ae1839f63b90a6c6829eed88874" FOREIGN KEY ("detailId") REFERENCES "registration_application_details"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_be6b8d137cc480508923911b0e2" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_eb17866a7060fead1cdcd06c476" FOREIGN KEY ("documentTypeId") REFERENCES "document_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submission_values" ADD CONSTRAINT "FK_080cbdd6b065bd47e2c9fc669e7" FOREIGN KEY ("submissionId") REFERENCES "form_submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_6bb44ead8acd515f1333e5309bf" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields_requests" ADD CONSTRAINT "FK_8f53f66f92db8c0349f583ce9db" FOREIGN KEY ("formRequestId") REFERENCES "form_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighing_history" ADD CONSTRAINT "FK_420976612b58fe9bec06d965c93" FOREIGN KEY ("weighingId") REFERENCES "weighing"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighing_history" ADD CONSTRAINT "FK_d07a787a1c21a374b1d68796a6e" FOREIGN KEY ("weighbridgeCalibrationCertificate") REFERENCES "warehouse_documents"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "weighing_history" ADD CONSTRAINT "FK_70b1f283730c20f6dde9fde6b21" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" ADD CONSTRAINT "FK_2d1b3ee6d0b70bf533902a47b5d" FOREIGN KEY ("technicalQualitativeId") REFERENCES "technical_qualitative"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" ADD CONSTRAINT "FK_1fce116ee6729a872de763e0225" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" ADD CONSTRAINT "FK_cd45d6d0937d5ac6a6a83477b9c" FOREIGN KEY ("jurisdictionId") REFERENCES "jurisdiction"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" ADD CONSTRAINT "FK_10313eb74a5f7c95770b0c27d03" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_history" ADD CONSTRAINT "FK_3888228dd434c0e526310620cf8" FOREIGN KEY ("securityId") REFERENCES "security"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "security_history" ADD CONSTRAINT "FK_022e8d2fc65553fb7470c3cf3cd" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" ADD CONSTRAINT "FK_818e10abf5d99a5e8fca4e2492e" FOREIGN KEY ("fireSafetyId") REFERENCES "fire_safety"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" ADD CONSTRAINT "FK_26366890b5ae02523c8bb61e510" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility_history" ADD CONSTRAINT "FK_98b9bcef9313f59c4be41e73ce8" FOREIGN KEY ("facilityId") REFERENCES "facility"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "facility_history" ADD CONSTRAINT "FK_b7133352bed6d2c7225e8814a0b" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_history" ADD CONSTRAINT "FK_4a93b3794827c600f020d827d05" FOREIGN KEY ("contactId") REFERENCES "contact"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contact_history" ADD CONSTRAINT "FK_0c3dc8902a378fab9b3fe15d818" FOREIGN KEY ("warehouseLocationId") REFERENCES "warehouse_location"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "contact_history" DROP CONSTRAINT "FK_0c3dc8902a378fab9b3fe15d818"`);
        await queryRunner.query(`ALTER TABLE "contact_history" DROP CONSTRAINT "FK_4a93b3794827c600f020d827d05"`);
        await queryRunner.query(`ALTER TABLE "facility_history" DROP CONSTRAINT "FK_b7133352bed6d2c7225e8814a0b"`);
        await queryRunner.query(`ALTER TABLE "facility_history" DROP CONSTRAINT "FK_98b9bcef9313f59c4be41e73ce8"`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" DROP CONSTRAINT "FK_26366890b5ae02523c8bb61e510"`);
        await queryRunner.query(`ALTER TABLE "fire_safety_history" DROP CONSTRAINT "FK_818e10abf5d99a5e8fca4e2492e"`);
        await queryRunner.query(`ALTER TABLE "security_history" DROP CONSTRAINT "FK_022e8d2fc65553fb7470c3cf3cd"`);
        await queryRunner.query(`ALTER TABLE "security_history" DROP CONSTRAINT "FK_3888228dd434c0e526310620cf8"`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" DROP CONSTRAINT "FK_10313eb74a5f7c95770b0c27d03"`);
        await queryRunner.query(`ALTER TABLE "jurisdiction_history" DROP CONSTRAINT "FK_cd45d6d0937d5ac6a6a83477b9c"`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" DROP CONSTRAINT "FK_1fce116ee6729a872de763e0225"`);
        await queryRunner.query(`ALTER TABLE "technical_qualitative_history" DROP CONSTRAINT "FK_2d1b3ee6d0b70bf533902a47b5d"`);
        await queryRunner.query(`ALTER TABLE "weighing_history" DROP CONSTRAINT "FK_70b1f283730c20f6dde9fde6b21"`);
        await queryRunner.query(`ALTER TABLE "weighing_history" DROP CONSTRAINT "FK_d07a787a1c21a374b1d68796a6e"`);
        await queryRunner.query(`ALTER TABLE "weighing_history" DROP CONSTRAINT "FK_420976612b58fe9bec06d965c93"`);
        await queryRunner.query(`ALTER TABLE "form_fields_requests" DROP CONSTRAINT "FK_8f53f66f92db8c0349f583ce9db"`);
        await queryRunner.query(`ALTER TABLE "form_submissions" DROP CONSTRAINT "FK_6bb44ead8acd515f1333e5309bf"`);
        await queryRunner.query(`ALTER TABLE "form_submission_values" DROP CONSTRAINT "FK_080cbdd6b065bd47e2c9fc669e7"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_eb17866a7060fead1cdcd06c476"`);
        await queryRunner.query(`ALTER TABLE "form_fields" DROP CONSTRAINT "FK_be6b8d137cc480508923911b0e2"`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" DROP CONSTRAINT "FK_ae1839f63b90a6c6829eed88874"`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" DROP CONSTRAINT "FK_1ae12e3d6aa7da17033a35d14aa"`);
        await queryRunner.query(`ALTER TABLE "registration_application" DROP CONSTRAINT "FK_5ce51bfeedd4654c6cbd1b563a9"`);
        await queryRunner.query(`ALTER TABLE "registration_application_details" DROP CONSTRAINT "FK_4860566b6279bc22f26a96f4ffc"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_86033897c009fcca8b6505d6be2"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_472b25323af01488f1f66a06b67"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_b4599f8b8f548d35850afa2d12c"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "UQ_88481b0c4ed9ada47e9fdd67475"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "UQ_d430a02aad006d8a70f3acd7d03"`);
        await queryRunner.query(`CREATE TYPE "public"."form_request_status_enum_old" AS ENUM('pending', 'approved', 'rejected')`);
        await queryRunner.query(`ALTER TABLE "form_requests" ALTER COLUMN "status" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "form_requests" ALTER COLUMN "status" TYPE "public"."form_request_status_enum_old" USING "status"::"text"::"public"."form_request_status_enum_old"`);
        await queryRunner.query(`ALTER TABLE "form_requests" ALTER COLUMN "status" SET DEFAULT 'pending'`);
        await queryRunner.query(`DROP TYPE "public"."form_requests_status_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."form_request_status_enum_old" RENAME TO "form_request_status_enum"`);
        await queryRunner.query(`ALTER TABLE "form_fields_requests" ALTER COLUMN "width" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "registration_application" DROP CONSTRAINT "UQ_5ce51bfeedd4654c6cbd1b563a9"`);
        await queryRunner.query(`ALTER TABLE "registration_application" ADD CONSTRAINT "FK_5ce51bfeedd4654c6cbd1b563a9" FOREIGN KEY ("applicationTypeId") REFERENCES "application_type"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."otpExpires" IS 'OTP expiration timestamp'`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."otp" IS 'One-time password for email verification'`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."passwordResetExpires" IS 'Password reset token expiration timestamp'`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."passwordResetToken" IS 'Token for password reset'`);
        await queryRunner.query(`COMMENT ON COLUMN "users"."refreshToken" IS 'Refresh token for JWT authentication'`);
        await queryRunner.query(`DROP TABLE "contact_history"`);
        await queryRunner.query(`DROP TABLE "facility_history"`);
        await queryRunner.query(`DROP TABLE "fire_safety_history"`);
        await queryRunner.query(`DROP TABLE "security_history"`);
        await queryRunner.query(`DROP TABLE "jurisdiction_history"`);
        await queryRunner.query(`DROP TABLE "technical_qualitative_history"`);
        await queryRunner.query(`DROP TABLE "weighing_history"`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "UQ_user_roles" UNIQUE ("userId", "roleId")`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "UQ_role_permissions" UNIQUE ("roleId", "permissionId")`);
        await queryRunner.query(`CREATE INDEX "IDX_form_requests_requestedBy" ON "form_requests" ("requestedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_requests_slug" ON "form_requests" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_requests_status" ON "form_requests" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_requests_formId" ON "form_requests" ("formId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_requests_action" ON "form_fields_requests" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_requests_fieldKey" ON "form_fields_requests" ("fieldKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_requests_formRequestId" ON "form_fields_requests" ("formRequestId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submissions_status" ON "form_submissions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submissions_userId" ON "form_submissions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submissions_formId" ON "form_submissions" ("formId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submission_values_fieldKey" ON "form_submission_values" ("fieldKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_submission_values_submissionId" ON "form_submission_values" ("submissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_documentTypeId" ON "form_fields" ("documentTypeId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_form_fields_formId_fieldKey" ON "form_fields" ("fieldKey", "formId") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_type" ON "form_fields" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_fieldKey" ON "form_fields" ("fieldKey") `);
        await queryRunner.query(`CREATE INDEX "IDX_form_fields_formId" ON "form_fields" ("formId") `);
        await queryRunner.query(`CREATE INDEX "IDX_forms_version" ON "forms" ("version") `);
        await queryRunner.query(`CREATE INDEX "IDX_forms_isActive" ON "forms" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_forms_isPublic" ON "forms" ("isPublic") `);
        await queryRunner.query(`CREATE INDEX "IDX_forms_status" ON "forms" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_forms_slug" ON "forms" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_registration_documents_detailId" ON "admin_registration_documents" ("detailId") `);
        await queryRunner.query(`CREATE INDEX "IDX_admin_registration_documents_applicationId" ON "admin_registration_documents" ("applicationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_registration_application_applicationId" ON "registration_application" ("applicationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_registration_application_details_documentTypeId" ON "registration_application_details" ("documentTypeId") `);
        await queryRunner.query(`CREATE INDEX "IDX_document_types_deletedAt" ON "document_types" ("deletedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_settings_key" ON "settings" ("key") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_roleId" ON "user_roles" ("roleId") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_userId" ON "user_roles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_permissionId" ON "role_permissions" ("permissionId") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_roleId" ON "role_permissions" ("roleId") `);
        await queryRunner.query(`ALTER TABLE "form_requests" ADD CONSTRAINT "FK_form_requests_formId" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields_requests" ADD CONSTRAINT "FK_form_fields_requests_formRequestId" FOREIGN KEY ("formRequestId") REFERENCES "form_requests"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submissions" ADD CONSTRAINT "FK_form_submissions_formId" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_submission_values" ADD CONSTRAINT "FK_form_submission_values_submissionId" FOREIGN KEY ("submissionId") REFERENCES "form_submissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_form_fields_document_type" FOREIGN KEY ("documentTypeId") REFERENCES "document_types"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "form_fields" ADD CONSTRAINT "FK_form_fields_formId" FOREIGN KEY ("formId") REFERENCES "forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" ADD CONSTRAINT "FK_admin_registration_documents_detailId" FOREIGN KEY ("detailId") REFERENCES "registration_application_details"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "admin_registration_documents" ADD CONSTRAINT "FK_admin_registration_documents_applicationId" FOREIGN KEY ("applicationId") REFERENCES "registration_application"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "registration_application_details" ADD CONSTRAINT "FK_registration_application_details_document_type" FOREIGN KEY ("documentTypeId") REFERENCES "document_types"("id") ON DELETE SET NULL ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_user_roles_role" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_user_roles_user" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_permission" FOREIGN KEY ("permissionId") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_role_permissions_role" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
    }

}
