export enum EntityType {
    APPLICANT_CHECKLIST = 'applicant_checklist',
    APPLICANT_DECLARATION_CHECKLIST = 'declaration_checklist',
    APPLICANT_FINANCIAL_SOUNDNESS_CHECKLIST = 'financial_soundness_checklist',
    APPLICANT_HUMAN_RESOURCES_CHECKLIST = 'human_resources_checklist',
    APPLICANT_REGISTRATION_FEE_CHECKLIST = 'registration_fee_checklist',
    COMPANY_INFORMATION = 'company_information',
    AUTHORIZED_SIGNATORY = 'authorized_signatories',
    BANK_DETAILS = 'bank_details',
    HR_INFORMATION = 'hrs',
    HR_ACADEMIC_QUALIFICATIONS = 'hr_academic_qualifications',
    HR_DECLARATION = 'hr_declaration',
    HR_EXPERIENCE = 'hr_experience',
    HR_PERSONAL_DETAILS = 'hr_personal_details',
    HR_PROFESSIONAL_QUALIFICATIONS = 'hr_professional_qualifications',
    HR_TRAININGS = 'hr_trainings',
    FINANCIAL_INFORMATION = 'financial_information',
    FINANCIAL_INFORMATION_AUDIT_REPORT = 'audit_report',
    FINANCIAL_INFORMATION_BANK_STATEMENT = 'bank_statement',
    FINANCIAL_INFORMATION_OTHERS = 'financial_others',
    FINANCIAL_INFORMATION_TAX_RETURNS = 'tax_return',
}